---
kind: pipeline
type: docker
name: Build

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: install deps
    image: node:20
    commands:
      - yarn

  - name: build
    image: node:20
    commands:
      - yarn build

  - name: zip
    image: alpine:3.20.3
    commands:
      - apk add zip
      - zip -r -v ./dist.zip ./build

  - name: upload artifact
    image: plugins/s3
    settings:
      bucket:
        from_secret: s3_bucket
      access_key:
        from_secret: s3_secret_id
      secret_key:
        from_secret: s3_secret_key
      endpoint:
        from_secret: s3_endpoint
      region:
        from_secret: s3_region
      source: dist.zip
      target: ${DRONE_REPO}/${DRONE_BUILD_NUMBER}

---
kind: pipeline
type: docker
name: Deploy

trigger:
  event:
    - promote
  target:
    - production

steps:
  - name: download artifact
    image: alpine:3.20.3
    environment:
      S3_HOST:
        from_secret: s3_host
    commands:
      - apk add unzip wget
      - wget $S3_HOST/$DRONE_REPO/$DRONE_BUILD_PARENT/dist.zip
      - unzip dist.zip

  - name: deploy
    image: plugins/s3
    settings:
      bucket:
        from_secret: deploy_s3_bucket
      access_key:
        from_secret: s3_secret_id
      secret_key:
        from_secret: s3_secret_key
      endpoint:
        from_secret: deploy_s3_endpoint
      region:
        from_secret: deploy_s3_region
      source: ./build/*
      target: .
